### ISSUE TITLE
The code needs to be in a new django "app" structure

### ISSUE THREAD

**Issue by Afrowave** [JoshData/django-annotator-store#1]
In django 1.10.4, I quickly loaded the app in the old way. And after running `makemigrations` and `migrate` I got this:

    django.db.utils.ProgrammingError: relation "" does not exist LINE 1: SELECT COUNT(*) AS "__count" FROM "annotator_annotation"

This needs an app in the new app structure.

**Comment by JoshData** [comment]
Thanks but I'm no longer maintaining this code. Feel free to fork. :)

**Comment by Afrowave** [comment]
Thank you for the code. I will.
